export interface CxcRow {
  id?: number;
  tipo: string | null;
  codfactol: string | null;
  fechaent: string | null;
  codcli: string | null;
  fechfactol: string | null;
  fecha: string | null;
  fechven: string | null;
  vence: string | null;
  vencidas: string | null;
  dias: number | null;
  valorfact: number | null;
  abonos: number | null;
  deudafa: number | null;
  nomcli: string | null;
  estadofac: string | null;
  nomgrupo: string | null;
  ciudad: string | null;
  dpto: string | null;
  utilidad: number | null;
  total_utilidad: number | null;
  comision: number | null;
  saldo_cxc: number | null;
  dias_mora: number | null;
  rango_mora: string | null;
  created_at?: string;
}

export interface CxpRow {
  id?: number;
  tipo: string | null;
  codfactol: string | null;
  codfacte: string | null;
  fechaent: string | null;
  codcli: string | null;
  fechfactol: string | null;
  nomcli: string | null;
  fechven: string | null;
  vencidas: string | null;
  valorfact: number | null;
  abonos: number | null;
  descuentos: number | null;
  reteica_vlr: number | null;
  reteiva_vlr: number | null;
  retecree_vlr: number | null;
  bruta: number | null;
  deudafa: number | null;
  grupocli: string | null;
  rtefte: number | null;
  tipo_tercero: string | null;
  estadofac: string | null;
  nomgrupo: string | null;
  plazo: number | null;
  nitpro: string | null;
  dv: string | null;
  telepro: string | null;
  telepro2: string | null;
  retencion: number | null;
  direpro: string | null;
  observacion: string | null;
  imp_observacion: string | null;
  otros: number | null;
  utilidad: number | null;
  total_utilidad: number | null;
  comision: number | null;
  tipoid: string | null;
  apellido1: string | null;
  apellido2: string | null;
  nombre1: string | null;
  nombre2: string | null;
  razon_social: string | null;
  tipo_documento: string | null;
  titulo: string | null;
  titulo2: string | null;
  seleccion: string | null;
  codciu: string | null;
  dias: number | null;
  ciudad: string | null;
  dpto: string | null;
  coddian_dpto: string | null;
  coddian_ciudad: string | null;
  saldo_cxp: number | null;
  dias_mora: number | null;
  rango_mora: string | null;
  created_at?: string;
}

export type AgingBucket = "0-30" | "31-60" | "61-90" | "90+";

